<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="simUiDsl" nsURI="http://www.dslconsultancy.com/simscript/ui/SimUiDsl"
    nsPrefix="simUiDsl">
  <eClassifiers xsi:type="ecore:EClass" name="UiModule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="notAuthenticated" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="definitions" upperBound="-1"
        eType="#//TopLevelDefinition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TopLevelDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameterList" eType="#//ParameterList"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableRowsDefinition" eSuperTypes="#//TopLevelDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rows" upperBound="-1" eType="#//TableRow"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Viewable" eSuperTypes="#//TopLevelDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//ViewableTypes"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DefinedViewable" eSuperTypes="#//Viewable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="valuesBlock" eType="#//ValuesBlock"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="definitions" upperBound="-1"
        eType="#//LocalViewableDefinition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ManualViewable" eSuperTypes="#//Viewable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="namespace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocalViewableDefinition"/>
  <eClassifiers xsi:type="ecore:EEnum" name="ViewableTypes">
    <eLiterals name="screen" literal="screen"/>
    <eLiterals name="component" value="1" literal="component"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValuesBlock">
    <eStructuralFeatures xsi:type="ecore:EReference" name="declarations" upperBound="-1"
        eType="#//ValueDeclaration" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValueDeclaration" eSuperTypes="#//AbstractValueDeclaration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueType" eType="#//ValueTypes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ValueTypes">
    <eLiterals name="variable" literal="="/>
    <eLiterals name="derived" value="1" literal="&lt;-"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Value" eSuperTypes="#//Referable"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractValueDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Value"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="declaredType" eType="ecore:EClass ../../../../../../nl.dslmeinte.simscript.structure/src-gen/nl/dslmeinte/simscript/structure/SimStructureDsl.ecore#//TypeLiteral"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueExpr" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter" eSuperTypes="#//Referable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass ../../../../../../nl.dslmeinte.simscript.structure/src-gen/nl/dslmeinte/simscript/structure/SimStructureDsl.ecore#//TypeLiteral"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Parameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MethodDefinition" eSuperTypes="#//TopLevelDefinition #//LocalViewableDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="method" eType="#//Method"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statementBlock" eType="#//StatementBlock"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Method" eSuperTypes="#//Referable"/>
  <eClassifiers xsi:type="ecore:EClass" name="Element" eSuperTypes="#//LocalViewableDefinition"/>
  <eClassifiers xsi:type="ecore:EClass" name="Quotation" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="path" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Binding" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bindSite" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElementBody">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//Element" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentInvocation" eSuperTypes="#//Element #//ViewableCallSite"/>
  <eClassifiers xsi:type="ecore:EClass" name="Argument">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" eType="#//Parameter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueExpr" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArgumentList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1"
        eType="#//Argument" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputElement" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bindSite" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hint" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="minValue" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="maxValue" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="radioOption" eType="#//RadioOption"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="onChange" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="onSubmit" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="structureOption" eType="#//StructureOption"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RadioOption">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="true" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StructureOption">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceExpr" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="displayFunction" eType="#//Method"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ButtonElement" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cssClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BlockElement" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="onClick" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cssClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bodyCssClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="style" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="header" eType="#//ElementBody"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="headerCssClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="noCss" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//ElementBody"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListElement" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="indexVariable" eType="#//ListVariable"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueVariable" eType="#//ListVariable"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listExpression" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//ElementBody"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListVariable" eSuperTypes="#//Referable"/>
  <eClassifiers xsi:type="ecore:EClass" name="TableElement" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subElements" upperBound="-1"
        eType="#//TableBodyElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableBodyElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="TableRowsInvocation" eSuperTypes="#//TableBodyElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="definition" eType="#//TableRowsDefinition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="argumentList" eType="#//ArgumentList"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableRow" eSuperTypes="#//TableBodyElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="label" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//ElementBody"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LabeledTableElement" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//ElementBody"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LabeledTableRow" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="label" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//ElementBody"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProgressBarTabSet" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tabs" upperBound="-1" eType="#//TabDeclaration"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TabDeclaration" eSuperTypes="#//ViewableCallSite">
    <eStructuralFeatures xsi:type="ecore:EReference" name="header" eType="#//ElementBody"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="previousCallback" eType="#//CallbackExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nextCallback" eType="#//CallbackExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GroupElement" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="orientation" eType="#//GroupOrientations"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="v_align" eType="#//VerticalAlignment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nestedGroups" upperBound="-1"
        eType="#//GroupElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="leafGroups" upperBound="-1"
        eType="#//ElementBody" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="GroupOrientations">
    <eLiterals name="vertical" literal="vertical"/>
    <eLiterals name="horizontal" value="1" literal="horizontal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="VerticalAlignment">
    <eLiterals name="top" literal="top"/>
    <eLiterals name="bottom" value="1" literal="bottom"/>
    <eLiterals name="middle" value="2" literal="middle"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CountdownTimer" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="observed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="endTime" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="onEnd" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObserveElement" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="observeExpr" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statementBlock" eType="#//StatementBlock"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CalendarElement" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="date" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="onSelect" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allowFrom" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateFormat" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="days" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cssClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TimeSlotListElement" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="slots" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="onSelect" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="onDelete" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SlotAddElement" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="product" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="day" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="slots" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="startHour" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="endHour" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WhenElement" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//ElementBody"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImageElement" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="observed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceUrl" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="width" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="height" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FrameElement" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceUrl" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="width" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="height" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LineBreakElement" eSuperTypes="#//Element"/>
  <eClassifiers xsi:type="ecore:EClass" name="StatementBlock">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1"
        eType="#//Statement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Statement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExitingStatement" eSuperTypes="#//Statement"/>
  <eClassifiers xsi:type="ecore:EClass" name="NonExitingStatement" eSuperTypes="#//Statement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ForStatement" eSuperTypes="#//NonExitingStatement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="indexVariable" eType="#//ListVariable"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueVariable" eType="#//ListVariable"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listExpression" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="thenBlock" eType="#//StatementBlock"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListRemoveStatement" eSuperTypes="#//NonExitingStatement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="listExpr" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" eType="ecore:EClass ../../../../../../nl.dslmeinte.simscript.structure/src-gen/nl/dslmeinte/simscript/structure/SimStructureDsl.ecore#//Feature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueExpr" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="indexVariable" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssignmentOrExpressionStatement" eSuperTypes="#//NonExitingStatement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lhs" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//AssignmentOperator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rhs" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AssignmentOperator">
    <eLiterals name="assign" literal="="/>
    <eLiterals name="add" value="1" literal="+="/>
    <eLiterals name="sub" value="2" literal="-="/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ShowModalStatement" eSuperTypes="#//NonExitingStatement #//ViewableCallSite">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="persistent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExitModalStatement" eSuperTypes="#//NonExitingStatement"/>
  <eClassifiers xsi:type="ecore:EClass" name="GotoScreenStatement" eSuperTypes="#//ExitingStatement #//ViewableCallSite"/>
  <eClassifiers xsi:type="ecore:EClass" name="GotoModuleStatement" eSuperTypes="#//ExitingStatement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetModule" eType="#//UiModule"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="args" eType="#//ArgumentList"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="authenticate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="authOption" eType="ecore:EClass ../../../../../../nl.dslmeinte.simscript.backend/src-gen/nl/dslmeinte/simscript/backend/SimBackendDsl.ecore#//AuthenticationDeclaration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="principal" eType="#//PrincipalArgument"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="credential" eType="#//CredentialArgument"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="errorCallback" eType="#//CallbackExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrincipalArgument">
    <eStructuralFeatures xsi:type="ecore:EReference" name="principal" eType="ecore:EClass ../../../../../../nl.dslmeinte.simscript.backend/src-gen/nl/dslmeinte/simscript/backend/SimBackendDsl.ecore#//AuthenticationParameter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueExpr" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CredentialArgument">
    <eStructuralFeatures xsi:type="ecore:EReference" name="credential" eType="ecore:EClass ../../../../../../nl.dslmeinte.simscript.backend/src-gen/nl/dslmeinte/simscript/backend/SimBackendDsl.ecore#//AuthenticationParameter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueExpr" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IfStatement" eSuperTypes="#//NonExitingStatement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="thenBlock" eType="#//StatementBlock"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elseBlock" eType="#//StatementBlock"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocalValueDeclarationStatement" eSuperTypes="#//AbstractValueDeclaration #//NonExitingStatement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ViewableCallSite">
    <eStructuralFeatures xsi:type="ecore:EReference" name="viewable" eType="#//Viewable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="argumentList" eType="#//ArgumentList"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Comparator">
    <eLiterals name="equals" literal="=="/>
    <eLiterals name="notEquals" value="1" literal="!="/>
    <eLiterals name="bigger" value="2" literal=">"/>
    <eLiterals name="biggerEquals" value="3" literal=">="/>
    <eLiterals name="smaller" value="4" literal="&lt;"/>
    <eLiterals name="smallerEquals" value="5" literal="&lt;="/>
    <eLiterals name="isIn" value="6" literal="in"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AdditiveOperators">
    <eLiterals name="plus" literal="+"/>
    <eLiterals name="minus" value="1" literal="-"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MultiplicativeOperators">
    <eLiterals name="mult" literal="*"/>
    <eLiterals name="div" value="1" literal="/"/>
    <eLiterals name="mod" value="2" literal="%"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceIdentification"/>
  <eClassifiers xsi:type="ecore:EEnum" name="CrudTypes">
    <eLiterals name="create" literal="create"/>
    <eLiterals name="getById" value="1" literal="get-by-id"/>
    <eLiterals name="update" value="2" literal="update"/>
    <eLiterals name="delete" value="3" literal="delete"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DateExpression" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="BuiltinFunctionExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="function" eType="#//BuiltinFunctions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="argument" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sortFeature" eType="ecore:EClass ../../../../../../nl.dslmeinte.simscript.structure/src-gen/nl/dslmeinte/simscript/structure/SimStructureDsl.ecore#//Feature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BuiltinFunctions">
    <eLiterals name="isSet" literal="isSet"/>
    <eLiterals name="alert" value="1" literal="alert"/>
    <eLiterals name="confirm" value="2" literal="confirm"/>
    <eLiterals name="copyOf" value="3" literal="copyOf"/>
    <eLiterals name="toMillis" value="4" literal="toMillis"/>
    <eLiterals name="round" value="5" literal="round"/>
    <eLiterals name="sort" value="6" literal="sort"/>
    <eLiterals name="isValid" value="7" literal="isValid"/>
    <eLiterals name="id" value="8" literal="id"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralExpression" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="ListLiteralExpression" eSuperTypes="#//LiteralExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="members" upperBound="-1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumerationLiteralExpression" eSuperTypes="#//LiteralExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enumeration" eType="ecore:EClass ../../../../../../nl.dslmeinte.simscript.structure/src-gen/nl/dslmeinte/simscript/structure/SimStructureDsl.ecore#//Enumeration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="literal" eType="ecore:EClass ../../../../../../nl.dslmeinte.simscript.structure/src-gen/nl/dslmeinte/simscript/structure/SimStructureDsl.ecore#//EnumerationLiteral"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BooleanLiterals">
    <eLiterals name="false" literal="false"/>
    <eLiterals name="true" value="1" literal="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DecisionExpression" eSuperTypes="#//LiteralExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cases" upperBound="-1"
        eType="#//DecisionCase" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultValueExpr" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DecisionCase">
    <eStructuralFeatures xsi:type="ecore:EReference" name="guardExpr" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueExpr" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CallbackExpressions" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="CallbackExpression" eSuperTypes="#//CallbackExpressions">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statementBlock" eType="#//StatementBlock"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StructureCreationExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="structure" eType="ecore:EClass ../../../../../../nl.dslmeinte.simscript.structure/src-gen/nl/dslmeinte/simscript/structure/SimStructureDsl.ecore#//Structure"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignments" upperBound="-1"
        eType="#//FeatureAssignment" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureAssignment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" eType="ecore:EClass ../../../../../../nl.dslmeinte.simscript.structure/src-gen/nl/dslmeinte/simscript/structure/SimStructureDsl.ecore#//Feature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueExpr" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValueReferenceOrMethodCallExpression"
      eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="ReferenceExpression" eSuperTypes="#//ValueReferenceOrMethodCallExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" eType="#//Referable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Referable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TernaryExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="guard" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="thenExpr" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elseExpr" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OrExpression" eSuperTypes="#//BooleanBinaryOperatorExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="AndExpression" eSuperTypes="#//BooleanBinaryOperatorExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="ComparisonExpression" eSuperTypes="#//BinaryOperatorExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comparator" eType="#//Comparator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AdditiveExpression" eSuperTypes="#//ArithmeticBinaryOperatorExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//AdditiveOperators"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MultiplicativeExpression" eSuperTypes="#//ArithmeticBinaryOperatorExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//MultiplicativeOperators"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NotExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operand" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InterfaceCallExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviceId" eType="#//ServiceIdentification"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="observeSites" upperBound="-1"
        eType="#//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="callback" eType="#//CallbackExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="errorCallback" eType="#//CallbackExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedServiceReference" eSuperTypes="#//ServiceIdentification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="service" eType="ecore:EClass ../../../../../../nl.dslmeinte.simscript.backend/src-gen/nl/dslmeinte/simscript/backend/SimBackendDsl.ecore#//NamedService"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CrudServiceIdentification" eSuperTypes="#//ServiceIdentification">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="crudType" eType="#//CrudTypes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="structure" eType="ecore:EClass ../../../../../../nl.dslmeinte.simscript.structure/src-gen/nl/dslmeinte/simscript/structure/SimStructureDsl.ecore#//Structure"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureAccessExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="previous" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" eType="ecore:EClass ../../../../../../nl.dslmeinte.simscript.structure/src-gen/nl/dslmeinte/simscript/structure/SimStructureDsl.ecore#//Feature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SelectionExpression" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="DateNowExpression" eSuperTypes="#//DateExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="DateTodayExpression" eSuperTypes="#//DateExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="StringLiteralExpression" eSuperTypes="#//LiteralExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanLiteralExpression" eSuperTypes="#//LiteralExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="literal" eType="#//BooleanLiterals"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerLiteralExpression" eSuperTypes="#//LiteralExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NumberLiteralExpression" eSuperTypes="#//LiteralExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CallbackResponseExpression" eSuperTypes="#//CallbackExpressions"/>
  <eClassifiers xsi:type="ecore:EClass" name="CallbackErrorResponseExpression" eSuperTypes="#//CallbackExpressions"/>
  <eClassifiers xsi:type="ecore:EClass" name="MethodCallExpression" eSuperTypes="#//ValueReferenceOrMethodCallExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="methodRef" eType="#//ReferenceExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="argumentList" eType="#//ArgumentList"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanBinaryOperatorExpression" eSuperTypes="#//BinaryOperatorExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="ArithmeticBinaryOperatorExpression"
      eSuperTypes="#//BinaryOperatorExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="BinaryOperatorExpression" abstract="true"
      eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="leftOperand" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rightOperand" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
