package com.simlike.simscript.generator.util

class GeneratorUtil {

	def header() {
		'''
		/*
		 * Generated by the SimScript plug-ins => do not modify!
		 */
		'''
	}

	def asJavadoc(String documentation) {
		documentation.replaceAll("\\n", "\n * ")
	}

}
