/*
* generated by Xtext
*/
package nl.dslmeinte.simscript.ui.ui.contentassist;

import nl.dslmeinte.simscript.ui.ui.contentassist.AbstractSimUiDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class SimUiDslProposalProvider extends AbstractSimUiDslProposalProvider {

}
