/*
* generated by Xtext
*/
package com.simlike.simscript.backend.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class SimBackendDslOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
