/*
* generated by Xtext
*/
package nl.dslmeinte.simscript.backend.ui.contentassist;

import nl.dslmeinte.simscript.backend.ui.contentassist.AbstractSimBackendDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class SimBackendDslProposalProvider extends AbstractSimBackendDslProposalProvider {

}
