/*
* generated by Xtext
*/
package nl.dslmeinte.simscript.mappings.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class MappingsDslOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
