/*
* generated by Xtext
*/
package nl.dslmeinte.simscript.ui.validation;
 
import java.util.ArrayList;
import java.util.List;

import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.ComposedChecks;

@ComposedChecks(validators= {org.eclipse.xtext.validation.NamesAreUniqueValidator.class})
public class AbstractSimUiDslJavaValidator extends nl.dslmeinte.simscript.structure.validation.SimStructureDslJavaValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(nl.dslmeinte.simscript.ui.simUiDsl.SimUiDslPackage.eINSTANCE);
		return result;
	}

}
