/*
 * generated by Xtext
 */
package com.simlike.simscript.structure.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SimStructureDslUiModule extends com.simlike.simscript.structure.ui.AbstractSimStructureDslUiModule {
	public SimStructureDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
