/*
 * generated by Xtext
 */
package nl.dslmeinte.simscript.ui.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import nl.dslmeinte.simscript.ui.ui.internal.SimUiDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SimUiDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SimUiDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SimUiDslActivator.getInstance().getInjector(SimUiDslActivator.NL_DSLMEINTE_SIMSCRIPT_UI_SIMUIDSL);
	}
	
}
