/*
 * generated by Xtext
 */
package com.simlike.simscript.backend.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SimBackendDslUiModule extends com.simlike.simscript.backend.ui.AbstractSimBackendDslUiModule {
	public SimBackendDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
