/*
 * generated by Xtext
 */
package com.simlike.simscript.application;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SimApplicationDslRuntimeModule extends com.simlike.simscript.application.AbstractSimApplicationDslRuntimeModule {

}
