/*
 * generated by Xtext
 */
package nl.dslmeinte.xtext.mappings.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MappingsDslUiModule extends nl.dslmeinte.xtext.mappings.ui.AbstractMappingsDslUiModule {
	public MappingsDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
