/*
* generated by Xtext
*/
package nl.dslmeinte.simscript.ui.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SimUiDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("nl/dslmeinte/simscript/ui/parser/antlr/internal/InternalSimUiDsl.tokens");
	}
}
