/*
* generated by Xtext
*/
package nl.dslmeinte.simscript.ui.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import nl.dslmeinte.simscript.ui.services.SimUiDslGrammarAccess;

public class SimUiDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private SimUiDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected nl.dslmeinte.simscript.ui.parser.antlr.internal.InternalSimUiDslParser createParser(XtextTokenStream stream) {
		return new nl.dslmeinte.simscript.ui.parser.antlr.internal.InternalSimUiDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "UiModule";
	}
	
	public SimUiDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SimUiDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
