/*
* generated by Xtext
*/
package nl.dslmeinte.simscript.application.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class SimApplicationDslOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
