/*
 * generated by Xtext
 */
package nl.dslmeinte.simscript.backend.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import nl.dslmeinte.simscript.backend.ui.internal.SimBackendDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SimBackendDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SimBackendDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SimBackendDslActivator.getInstance().getInjector(SimBackendDslActivator.NL_DSLMEINTE_SIMSCRIPT_BACKEND_SIMBACKENDDSL);
	}
	
}
