/*
* generated by Xtext
*/
package com.simlike.simscript.application.ui.contentassist;

import com.simlike.simscript.application.ui.contentassist.AbstractSimApplicationDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class SimApplicationDslProposalProvider extends AbstractSimApplicationDslProposalProvider {

}
