/*
* generated by Xtext
*/
package nl.dslmeinte.simscript.backend.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import nl.dslmeinte.simscript.backend.services.SimBackendDslGrammarAccess;

public class SimBackendDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private SimBackendDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected nl.dslmeinte.simscript.backend.parser.antlr.internal.InternalSimBackendDslParser createParser(XtextTokenStream stream) {
		return new nl.dslmeinte.simscript.backend.parser.antlr.internal.InternalSimBackendDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "BackendModel";
	}
	
	public SimBackendDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SimBackendDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
