/*
* generated by Xtext
*/
package nl.dslmeinte.simscript.backend.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SimBackendDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("nl/dslmeinte/simscript/backend/parser/antlr/internal/InternalSimBackendDsl.tokens");
	}
}
