/*
* generated by Xtext
*/
package nl.dslmeinte.simscript.structure.ui.contentassist;

import nl.dslmeinte.simscript.structure.ui.contentassist.AbstractSimStructureDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class SimStructureDslProposalProvider extends AbstractSimStructureDslProposalProvider {

}
