<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="structureDsl" nsURI="http://www.dslconsultancy.com/simscript/structure/StructureDsl"
    nsPrefix="structureDsl">
  <eClassifiers xsi:type="ecore:EClass" name="StructureModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeDefinitions" upperBound="-1"
        eType="#//DefinedType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DefinedType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Structure" eSuperTypes="#//DefinedType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="persistent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        containment="true">
      <eGenericType eClassifier="#//Feature">
        <eTypeArguments eClassifier="#//TypeLiteral"/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Feature">
    <eTypeParameters name="T">
      <eBounds eClassifier="#//TypeLiteral"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optional" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" containment="true">
      <eGenericType eTypeParameter="#//Feature/T"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Enumeration" eSuperTypes="#//DefinedType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="literals" upperBound="-1"
        eType="#//EnumerationLiteral" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumerationLiteral">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="displayName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeLiteral"/>
  <eClassifiers xsi:type="ecore:EClass" name="BuiltinTypeLiteral" eSuperTypes="#//TypeLiteral">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="builtin" eType="#//BuiltinTypes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BuiltinTypes">
    <eLiterals name="string" literal="String"/>
    <eLiterals name="boolean" value="1" literal="Boolean"/>
    <eLiterals name="integer" value="2" literal="Integer"/>
    <eLiterals name="url" value="3" literal="URL"/>
    <eLiterals name="text" value="4" literal="Text"/>
    <eLiterals name="number" value="5" literal="Number"/>
    <eLiterals name="email" value="6" literal="Email"/>
    <eLiterals name="phone" value="7" literal="Phone"/>
    <eLiterals name="date" value="8" literal="Date"/>
    <eLiterals name="password" value="9" literal="Password"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DefinedTypeLiteral" eSuperTypes="#//TypeLiteral">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//DefinedType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListTypeLiteral" eSuperTypes="#//TypeLiteral">
    <eStructuralFeatures xsi:type="ecore:EReference" name="itemType" eType="#//TypeLiteral"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SyntheticTypeLiteral" eSuperTypes="#//TypeLiteral"/>
  <eClassifiers xsi:type="ecore:EClass" name="CallbackLiteral" eSuperTypes="#//SyntheticTypeLiteral"/>
  <eClassifiers xsi:type="ecore:EClass" name="CallbackErrorResponseLiteral" eSuperTypes="#//SyntheticTypeLiteral"/>
  <eClassifiers xsi:type="ecore:EClass" name="VoidLiteral" eSuperTypes="#//SyntheticTypeLiteral"/>
</ecore:EPackage>
