<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="simBackendDsl" nsURI="http://www.dslconsultancy.com/simscript/backend/SimBackendDsl"
    nsPrefix="simBackendDsl">
  <eClassifiers xsi:type="ecore:EClass" name="BackendModel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baseUrl" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="flavor" eType="#//Flavors"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="authOpts" upperBound="-1"
        eType="#//AuthenticationDeclaration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="declarations" upperBound="-1"
        eType="#//Service" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Flavors">
    <eLiterals name="java" literal="Java"/>
    <eLiterals name="php" value="1" literal="PHP"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuthenticationDeclaration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="principal" eType="#//AuthenticationParameter"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="credential" eType="#//AuthenticationParameter"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuthenticationParameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass ../../../../../../nl.dslmeinte.simscript.structure/src-gen/nl/dslmeinte/simscript/structure/SimStructureDsl.ecore#//TypeLiteral"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Service"/>
  <eClassifiers xsi:type="ecore:EClass" name="NamedService" eSuperTypes="#//Service">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Interface" eSuperTypes="#//NamedService">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="method" eType="#//HttpMethods"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputType" eType="ecore:EClass ../../../../../../nl.dslmeinte.simscript.structure/src-gen/nl/dslmeinte/simscript/structure/SimStructureDsl.ecore#//DefinedTypeLiteral"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputType" eType="ecore:EClass ../../../../../../nl.dslmeinte.simscript.structure/src-gen/nl/dslmeinte/simscript/structure/SimStructureDsl.ecore#//TypeLiteral"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="notAuthenticated" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="legacyServlet" eType="#//LegacyServlet"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="documentation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="HttpMethods">
    <eLiterals name="get" literal="GET"/>
    <eLiterals name="post" value="1" literal="POST"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LegacyServlet" eSuperTypes="#//NamedService">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="urlPattern" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fqClassName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CrudService" eSuperTypes="#//Service">
    <eStructuralFeatures xsi:type="ecore:EReference" name="structure" eType="ecore:EClass ../../../../../../nl.dslmeinte.simscript.structure/src-gen/nl/dslmeinte/simscript/structure/SimStructureDsl.ecore#//Structure"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="services" unique="false"
        upperBound="-1" eType="#//CrudTypes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CrudTypes">
    <eLiterals name="create" literal="create"/>
    <eLiterals name="getById" value="1" literal="get-by-id"/>
    <eLiterals name="update" value="2" literal="update"/>
    <eLiterals name="delete" value="3" literal="delete"/>
  </eClassifiers>
</ecore:EPackage>
