/*
 * generated by Xtext
 */
package com.simlike.simscript.backend;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SimBackendDslRuntimeModule extends com.simlike.simscript.backend.AbstractSimBackendDslRuntimeModule {

}
