<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="simApplicationDsl" nsURI="http://www.dslconsultancy.com/simscript/application/SimApplicationDsl"
    nsPrefix="simApplicationDsl">
  <eClassifiers xsi:type="ecore:EClass" name="ApplicationModel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetPlatform" eType="#//TargetPlatforms"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="includeCSSs" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultCSS" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="includedModules" unique="false"
        upperBound="-1" eType="ecore:EClass ../../../../../../nl.dslmeinte.simscript.ui/src-gen/nl/dslmeinte/simscript/ui/SimUiDsl.ecore#//UiModule"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entryModule" eType="ecore:EClass ../../../../../../nl.dslmeinte.simscript.ui/src-gen/nl/dslmeinte/simscript/ui/SimUiDsl.ecore#//UiModule"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="includeCustomJS" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cHtmlHead" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cHtmlBody" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="genericBackButtonPrevention"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TargetPlatforms">
    <eLiterals name="html5" literal="html5"/>
    <eLiterals name="facebook" value="1" literal="facebook"/>
    <eLiterals name="mobile" value="2" literal="mobile"/>
  </eClassifiers>
</ecore:EPackage>
