/*
 * generated by Xtext
 */
package com.simlike.simscript.ui.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SimUiDslUiModule extends com.simlike.simscript.ui.ui.AbstractSimUiDslUiModule {
	public SimUiDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
