/*
 * generated by Xtext
 */
package nl.dslmeinte.simscript.structure.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SimStructureDslUiModule extends nl.dslmeinte.simscript.structure.ui.AbstractSimStructureDslUiModule {
	public SimStructureDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
