/*
* generated by Xtext
*/
package nl.dslmeinte.simscript.application.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SimApplicationDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("nl/dslmeinte/simscript/application/parser/antlr/internal/InternalSimApplicationDsl.tokens");
	}
}
