/*
* generated by Xtext
*/
package nl.dslmeinte.simscript.application.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import nl.dslmeinte.simscript.application.services.SimApplicationDslGrammarAccess;

public class SimApplicationDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private SimApplicationDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected nl.dslmeinte.simscript.application.parser.antlr.internal.InternalSimApplicationDslParser createParser(XtextTokenStream stream) {
		return new nl.dslmeinte.simscript.application.parser.antlr.internal.InternalSimApplicationDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "ApplicationModel";
	}
	
	public SimApplicationDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SimApplicationDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
