/*
* generated by Xtext
*/
package nl.dslmeinte.simscript.application.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class SimApplicationDslGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class ApplicationModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ApplicationModel");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cApplicationKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cTitleKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cEqualsSignKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cTitleAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cTitleSTRINGTerminalRuleCall_3_0 = (RuleCall)cTitleAssignment_3.eContents().get(0);
		private final Keyword cTargetPlatformKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cEqualsSignKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cTargetPlatformAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cTargetPlatformTargetPlatformsEnumRuleCall_6_0 = (RuleCall)cTargetPlatformAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cIncludeCssKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cIncludeCSSsAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cIncludeCSSsSTRINGTerminalRuleCall_7_1_0 = (RuleCall)cIncludeCSSsAssignment_7_1.eContents().get(0);
		private final Assignment cDefaultCSSAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final Keyword cDefaultCSSWithDefaultCssKeyword_8_0 = (Keyword)cDefaultCSSAssignment_8.eContents().get(0);
		private final Keyword cIncludedModulesKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cIncludedModulesAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final CrossReference cIncludedModulesUiModuleCrossReference_10_0 = (CrossReference)cIncludedModulesAssignment_10.eContents().get(0);
		private final RuleCall cIncludedModulesUiModuleIDTerminalRuleCall_10_0_1 = (RuleCall)cIncludedModulesUiModuleCrossReference_10_0.eContents().get(1);
		private final Keyword cEntryModuleKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Keyword cEqualsSignKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Assignment cEntryModuleAssignment_13 = (Assignment)cGroup.eContents().get(13);
		private final CrossReference cEntryModuleUiModuleCrossReference_13_0 = (CrossReference)cEntryModuleAssignment_13.eContents().get(0);
		private final RuleCall cEntryModuleUiModuleIDTerminalRuleCall_13_0_1 = (RuleCall)cEntryModuleUiModuleCrossReference_13_0.eContents().get(1);
		private final Group cGroup_14 = (Group)cGroup.eContents().get(14);
		private final Keyword cIncludeCustomJavaScriptKeyword_14_0 = (Keyword)cGroup_14.eContents().get(0);
		private final Assignment cIncludeCustomJSAssignment_14_1 = (Assignment)cGroup_14.eContents().get(1);
		private final RuleCall cIncludeCustomJSSTRINGTerminalRuleCall_14_1_0 = (RuleCall)cIncludeCustomJSAssignment_14_1.eContents().get(0);
		private final Group cGroup_15 = (Group)cGroup.eContents().get(15);
		private final Keyword cCustomHtmlHeadAdditionsKeyword_15_0 = (Keyword)cGroup_15.eContents().get(0);
		private final Keyword cEqualsSignKeyword_15_1 = (Keyword)cGroup_15.eContents().get(1);
		private final Assignment cCHtmlHeadAssignment_15_2 = (Assignment)cGroup_15.eContents().get(2);
		private final RuleCall cCHtmlHeadSTRINGTerminalRuleCall_15_2_0 = (RuleCall)cCHtmlHeadAssignment_15_2.eContents().get(0);
		private final Group cGroup_16 = (Group)cGroup.eContents().get(16);
		private final Keyword cCustomHtmlBodyKeyword_16_0 = (Keyword)cGroup_16.eContents().get(0);
		private final Keyword cEqualsSignKeyword_16_1 = (Keyword)cGroup_16.eContents().get(1);
		private final Assignment cCHtmlBodyAssignment_16_2 = (Assignment)cGroup_16.eContents().get(2);
		private final RuleCall cCHtmlBodySTRINGTerminalRuleCall_16_2_0 = (RuleCall)cCHtmlBodyAssignment_16_2.eContents().get(0);
		private final Assignment cGenericBackButtonPreventionAssignment_17 = (Assignment)cGroup.eContents().get(17);
		private final Keyword cGenericBackButtonPreventionWithGenericBackButtonPreventionKeyword_17_0 = (Keyword)cGenericBackButtonPreventionAssignment_17.eContents().get(0);
		
		//ApplicationModel:
		//	"application" "title" "=" title=STRING "target-platform" "=" targetPlatform=TargetPlatforms ("include-css"
		//	includeCSSs+=STRING*)? defaultCSS?="with-default-css"? "included-modules" includedModules+=[ui::UiModule]*
		//	"entry-module" "=" entryModule=[ui::UiModule] ("include-custom-JavaScript" includeCustomJS+=STRING*)?
		//	("custom-html-head-additions" "=" cHtmlHead=STRING)? ("custom-html-body" "=" cHtmlBody=STRING)?
		//	genericBackButtonPrevention?="with-generic-back-button-prevention"?;
		public ParserRule getRule() { return rule; }

		//"application" "title" "=" title=STRING "target-platform" "=" targetPlatform=TargetPlatforms ("include-css"
		//includeCSSs+=STRING*)? defaultCSS?="with-default-css"? "included-modules" includedModules+=[ui::UiModule]*
		//"entry-module" "=" entryModule=[ui::UiModule] ("include-custom-JavaScript" includeCustomJS+=STRING*)?
		//("custom-html-head-additions" "=" cHtmlHead=STRING)? ("custom-html-body" "=" cHtmlBody=STRING)?
		//genericBackButtonPrevention?="with-generic-back-button-prevention"?
		public Group getGroup() { return cGroup; }

		//"application"
		public Keyword getApplicationKeyword_0() { return cApplicationKeyword_0; }

		//"title"
		public Keyword getTitleKeyword_1() { return cTitleKeyword_1; }

		//"="
		public Keyword getEqualsSignKeyword_2() { return cEqualsSignKeyword_2; }

		//title=STRING
		public Assignment getTitleAssignment_3() { return cTitleAssignment_3; }

		//STRING
		public RuleCall getTitleSTRINGTerminalRuleCall_3_0() { return cTitleSTRINGTerminalRuleCall_3_0; }

		//"target-platform"
		public Keyword getTargetPlatformKeyword_4() { return cTargetPlatformKeyword_4; }

		//"="
		public Keyword getEqualsSignKeyword_5() { return cEqualsSignKeyword_5; }

		//targetPlatform=TargetPlatforms
		public Assignment getTargetPlatformAssignment_6() { return cTargetPlatformAssignment_6; }

		//TargetPlatforms
		public RuleCall getTargetPlatformTargetPlatformsEnumRuleCall_6_0() { return cTargetPlatformTargetPlatformsEnumRuleCall_6_0; }

		//("include-css" includeCSSs+=STRING*)?
		public Group getGroup_7() { return cGroup_7; }

		//"include-css"
		public Keyword getIncludeCssKeyword_7_0() { return cIncludeCssKeyword_7_0; }

		//includeCSSs+=STRING*
		public Assignment getIncludeCSSsAssignment_7_1() { return cIncludeCSSsAssignment_7_1; }

		//STRING
		public RuleCall getIncludeCSSsSTRINGTerminalRuleCall_7_1_0() { return cIncludeCSSsSTRINGTerminalRuleCall_7_1_0; }

		//defaultCSS?="with-default-css"?
		public Assignment getDefaultCSSAssignment_8() { return cDefaultCSSAssignment_8; }

		//"with-default-css"
		public Keyword getDefaultCSSWithDefaultCssKeyword_8_0() { return cDefaultCSSWithDefaultCssKeyword_8_0; }

		//"included-modules"
		public Keyword getIncludedModulesKeyword_9() { return cIncludedModulesKeyword_9; }

		//includedModules+=[ui::UiModule]*
		public Assignment getIncludedModulesAssignment_10() { return cIncludedModulesAssignment_10; }

		//[ui::UiModule]
		public CrossReference getIncludedModulesUiModuleCrossReference_10_0() { return cIncludedModulesUiModuleCrossReference_10_0; }

		//ID
		public RuleCall getIncludedModulesUiModuleIDTerminalRuleCall_10_0_1() { return cIncludedModulesUiModuleIDTerminalRuleCall_10_0_1; }

		//"entry-module"
		public Keyword getEntryModuleKeyword_11() { return cEntryModuleKeyword_11; }

		//"="
		public Keyword getEqualsSignKeyword_12() { return cEqualsSignKeyword_12; }

		//entryModule=[ui::UiModule]
		public Assignment getEntryModuleAssignment_13() { return cEntryModuleAssignment_13; }

		//[ui::UiModule]
		public CrossReference getEntryModuleUiModuleCrossReference_13_0() { return cEntryModuleUiModuleCrossReference_13_0; }

		//ID
		public RuleCall getEntryModuleUiModuleIDTerminalRuleCall_13_0_1() { return cEntryModuleUiModuleIDTerminalRuleCall_13_0_1; }

		//("include-custom-JavaScript" includeCustomJS+=STRING*)?
		public Group getGroup_14() { return cGroup_14; }

		//"include-custom-JavaScript"
		public Keyword getIncludeCustomJavaScriptKeyword_14_0() { return cIncludeCustomJavaScriptKeyword_14_0; }

		//includeCustomJS+=STRING*
		public Assignment getIncludeCustomJSAssignment_14_1() { return cIncludeCustomJSAssignment_14_1; }

		//STRING
		public RuleCall getIncludeCustomJSSTRINGTerminalRuleCall_14_1_0() { return cIncludeCustomJSSTRINGTerminalRuleCall_14_1_0; }

		//("custom-html-head-additions" "=" cHtmlHead=STRING)?
		public Group getGroup_15() { return cGroup_15; }

		//"custom-html-head-additions"
		public Keyword getCustomHtmlHeadAdditionsKeyword_15_0() { return cCustomHtmlHeadAdditionsKeyword_15_0; }

		//"="
		public Keyword getEqualsSignKeyword_15_1() { return cEqualsSignKeyword_15_1; }

		//cHtmlHead=STRING
		public Assignment getCHtmlHeadAssignment_15_2() { return cCHtmlHeadAssignment_15_2; }

		//STRING
		public RuleCall getCHtmlHeadSTRINGTerminalRuleCall_15_2_0() { return cCHtmlHeadSTRINGTerminalRuleCall_15_2_0; }

		//("custom-html-body" "=" cHtmlBody=STRING)?
		public Group getGroup_16() { return cGroup_16; }

		//"custom-html-body"
		public Keyword getCustomHtmlBodyKeyword_16_0() { return cCustomHtmlBodyKeyword_16_0; }

		//"="
		public Keyword getEqualsSignKeyword_16_1() { return cEqualsSignKeyword_16_1; }

		//cHtmlBody=STRING
		public Assignment getCHtmlBodyAssignment_16_2() { return cCHtmlBodyAssignment_16_2; }

		//STRING
		public RuleCall getCHtmlBodySTRINGTerminalRuleCall_16_2_0() { return cCHtmlBodySTRINGTerminalRuleCall_16_2_0; }

		//genericBackButtonPrevention?="with-generic-back-button-prevention"?
		public Assignment getGenericBackButtonPreventionAssignment_17() { return cGenericBackButtonPreventionAssignment_17; }

		//"with-generic-back-button-prevention"
		public Keyword getGenericBackButtonPreventionWithGenericBackButtonPreventionKeyword_17_0() { return cGenericBackButtonPreventionWithGenericBackButtonPreventionKeyword_17_0; }
	}
	
	
	public class TargetPlatformsElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "TargetPlatforms");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cHtml5EnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cHtml5Html5Keyword_0_0 = (Keyword)cHtml5EnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cFacebookEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cFacebookFacebookKeyword_1_0 = (Keyword)cFacebookEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cMobileEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cMobileMobileKeyword_2_0 = (Keyword)cMobileEnumLiteralDeclaration_2.eContents().get(0);
		
		//// scoping: entryModule in [containing(ApplicationModel)].modules	[√]
		//// TODO  define authentication
		/// *
		// * Various possible strategies:
		// * 		1. Point to a HTML file which has some place holders which searched and replaced.
		// * 		2. Customize specific elements of an HTML file that is for the most part generated.
		// * / enum TargetPlatforms:
		//	html5 | facebook | mobile;
		public EnumRule getRule() { return rule; }

		//html5 | facebook | mobile
		public Alternatives getAlternatives() { return cAlternatives; }

		//html5
		public EnumLiteralDeclaration getHtml5EnumLiteralDeclaration_0() { return cHtml5EnumLiteralDeclaration_0; }

		//"html5"
		public Keyword getHtml5Html5Keyword_0_0() { return cHtml5Html5Keyword_0_0; }

		//facebook
		public EnumLiteralDeclaration getFacebookEnumLiteralDeclaration_1() { return cFacebookEnumLiteralDeclaration_1; }

		//"facebook"
		public Keyword getFacebookFacebookKeyword_1_0() { return cFacebookFacebookKeyword_1_0; }

		//mobile
		public EnumLiteralDeclaration getMobileEnumLiteralDeclaration_2() { return cMobileEnumLiteralDeclaration_2; }

		//"mobile"
		public Keyword getMobileMobileKeyword_2_0() { return cMobileMobileKeyword_2_0; }
	}
	
	private ApplicationModelElements pApplicationModel;
	private TargetPlatformsElements unknownRuleTargetPlatforms;
	
	private final Grammar grammar;

	private TerminalsGrammarAccess gaTerminals;

	@Inject
	public SimApplicationDslGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("nl.dslmeinte.simscript.application.SimApplicationDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//ApplicationModel:
	//	"application" "title" "=" title=STRING "target-platform" "=" targetPlatform=TargetPlatforms ("include-css"
	//	includeCSSs+=STRING*)? defaultCSS?="with-default-css"? "included-modules" includedModules+=[ui::UiModule]*
	//	"entry-module" "=" entryModule=[ui::UiModule] ("include-custom-JavaScript" includeCustomJS+=STRING*)?
	//	("custom-html-head-additions" "=" cHtmlHead=STRING)? ("custom-html-body" "=" cHtmlBody=STRING)?
	//	genericBackButtonPrevention?="with-generic-back-button-prevention"?;
	public ApplicationModelElements getApplicationModelAccess() {
		return (pApplicationModel != null) ? pApplicationModel : (pApplicationModel = new ApplicationModelElements());
	}
	
	public ParserRule getApplicationModelRule() {
		return getApplicationModelAccess().getRule();
	}

	//// scoping: entryModule in [containing(ApplicationModel)].modules	[√]
	//// TODO  define authentication
	/// *
	// * Various possible strategies:
	// * 		1. Point to a HTML file which has some place holders which searched and replaced.
	// * 		2. Customize specific elements of an HTML file that is for the most part generated.
	// * / enum TargetPlatforms:
	//	html5 | facebook | mobile;
	public TargetPlatformsElements getTargetPlatformsAccess() {
		return (unknownRuleTargetPlatforms != null) ? unknownRuleTargetPlatforms : (unknownRuleTargetPlatforms = new TargetPlatformsElements());
	}
	
	public EnumRule getTargetPlatformsRule() {
		return getTargetPlatformsAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
