/*
 * generated by Xtext
 */
package nl.dslmeinte.simscript.application.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import nl.dslmeinte.simscript.application.ui.internal.SimApplicationDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SimApplicationDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SimApplicationDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SimApplicationDslActivator.getInstance().getInjector(SimApplicationDslActivator.NL_DSLMEINTE_SIMSCRIPT_APPLICATION_SIMAPPLICATIONDSL);
	}
	
}
