/*
* generated by Xtext
*/
package nl.dslmeinte.simscript.structure.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import nl.dslmeinte.simscript.structure.services.SimStructureDslGrammarAccess;

public class SimStructureDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private SimStructureDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected nl.dslmeinte.simscript.structure.parser.antlr.internal.InternalSimStructureDslParser createParser(XtextTokenStream stream) {
		return new nl.dslmeinte.simscript.structure.parser.antlr.internal.InternalSimStructureDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "StructureModel";
	}
	
	public SimStructureDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SimStructureDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
