/*
* generated by Xtext
*/
package nl.dslmeinte.simscript.structure.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SimStructureDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("nl/dslmeinte/simscript/structure/parser/antlr/internal/InternalSimStructureDsl.tokens");
	}
}
