/*
 * generated by Xtext
 */
package nl.dslmeinte.simscript.backend;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SimBackendDslRuntimeModule extends nl.dslmeinte.simscript.backend.AbstractSimBackendDslRuntimeModule {

}
