/*
* generated by Xtext
*/
package nl.dslmeinte.xtext.mappings.ui.contentassist;

import nl.dslmeinte.xtext.mappings.ui.contentassist.AbstractMappingsDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class MappingsDslProposalProvider extends AbstractMappingsDslProposalProvider {

}
