/*
 * generated by Xtext
 */
package nl.dslmeinte.xtext.simpleDb.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SimpleDbDslUiModule extends nl.dslmeinte.xtext.simpleDb.ui.AbstractSimpleDbDslUiModule {
	public SimpleDbDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
