/*
* generated by Xtext
*/
package nl.dslmeinte.simscript.simpleDb.ui.contentassist;

import nl.dslmeinte.simscript.simpleDb.ui.contentassist.AbstractSimpleDbDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class SimpleDbDslProposalProvider extends AbstractSimpleDbDslProposalProvider {

}
