/*
* generated by Xtext
*/
package nl.dslmeinte.simscript.backend.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import nl.dslmeinte.simscript.backend.services.SimBackendDslGrammarAccess;

public class SimBackendDslParser extends AbstractContentAssistParser {
	
	@Inject
	private SimBackendDslGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected nl.dslmeinte.simscript.backend.ui.contentassist.antlr.internal.InternalSimBackendDslParser createParser() {
		nl.dslmeinte.simscript.backend.ui.contentassist.antlr.internal.InternalSimBackendDslParser result = new nl.dslmeinte.simscript.backend.ui.contentassist.antlr.internal.InternalSimBackendDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getServiceAccess().getAlternatives(), "rule__Service__Alternatives");
					put(grammarAccess.getNamedServiceAccess().getAlternatives(), "rule__NamedService__Alternatives");
					put(grammarAccess.getDefinedTypeAccess().getAlternatives(), "rule__DefinedType__Alternatives");
					put(grammarAccess.getEnumerationNameAccess().getAlternatives(), "rule__EnumerationName__Alternatives");
					put(grammarAccess.getTypeLiteralAccess().getAlternatives(), "rule__TypeLiteral__Alternatives");
					put(grammarAccess.getSyntheticTypeLiteralAccess().getAlternatives(), "rule__SyntheticTypeLiteral__Alternatives");
					put(grammarAccess.getFlavorsAccess().getAlternatives(), "rule__Flavors__Alternatives");
					put(grammarAccess.getHttpMethodsAccess().getAlternatives(), "rule__HttpMethods__Alternatives");
					put(grammarAccess.getCrudTypesAccess().getAlternatives(), "rule__CrudTypes__Alternatives");
					put(grammarAccess.getBuiltinTypesAccess().getAlternatives(), "rule__BuiltinTypes__Alternatives");
					put(grammarAccess.getBackendModelAccess().getGroup(), "rule__BackendModel__Group__0");
					put(grammarAccess.getBackendModelAccess().getGroup_1_0(), "rule__BackendModel__Group_1_0__0");
					put(grammarAccess.getBackendModelAccess().getGroup_1_0_2(), "rule__BackendModel__Group_1_0_2__0");
					put(grammarAccess.getBackendModelAccess().getGroup_1_1(), "rule__BackendModel__Group_1_1__0");
					put(grammarAccess.getBackendModelAccess().getGroup_1_1_0(), "rule__BackendModel__Group_1_1_0__0");
					put(grammarAccess.getAuthenticationDeclarationAccess().getGroup(), "rule__AuthenticationDeclaration__Group__0");
					put(grammarAccess.getAuthenticationParameterAccess().getGroup(), "rule__AuthenticationParameter__Group__0");
					put(grammarAccess.getInterfaceAccess().getGroup(), "rule__Interface__Group__0");
					put(grammarAccess.getInterfaceAccess().getGroup_4(), "rule__Interface__Group_4__0");
					put(grammarAccess.getInterfaceAccess().getGroup_6(), "rule__Interface__Group_6__0");
					put(grammarAccess.getLegacyServletAccess().getGroup(), "rule__LegacyServlet__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup(), "rule__QualifiedName__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup_1(), "rule__QualifiedName__Group_1__0");
					put(grammarAccess.getCrudServiceAccess().getGroup(), "rule__CrudService__Group__0");
					put(grammarAccess.getStructureDefinitionAccess().getGroup(), "rule__StructureDefinition__Group__0");
					put(grammarAccess.getFeatureAccess().getGroup(), "rule__Feature__Group__0");
					put(grammarAccess.getEnumerationDefinitionAccess().getGroup(), "rule__EnumerationDefinition__Group__0");
					put(grammarAccess.getEnumerationLiteralAccess().getGroup(), "rule__EnumerationLiteral__Group__0");
					put(grammarAccess.getListTypeLiteralAccess().getGroup(), "rule__ListTypeLiteral__Group__0");
					put(grammarAccess.getSyntheticTypeLiteralAccess().getGroup_0(), "rule__SyntheticTypeLiteral__Group_0__0");
					put(grammarAccess.getSyntheticTypeLiteralAccess().getGroup_1(), "rule__SyntheticTypeLiteral__Group_1__0");
					put(grammarAccess.getSyntheticTypeLiteralAccess().getGroup_2(), "rule__SyntheticTypeLiteral__Group_2__0");
					put(grammarAccess.getBackendModelAccess().getBaseUrlAssignment_1_0_2_2(), "rule__BackendModel__BaseUrlAssignment_1_0_2_2");
					put(grammarAccess.getBackendModelAccess().getFlavorAssignment_1_1_0_2(), "rule__BackendModel__FlavorAssignment_1_1_0_2");
					put(grammarAccess.getBackendModelAccess().getAuthOptsAssignment_2(), "rule__BackendModel__AuthOptsAssignment_2");
					put(grammarAccess.getBackendModelAccess().getDeclarationsAssignment_3(), "rule__BackendModel__DeclarationsAssignment_3");
					put(grammarAccess.getAuthenticationDeclarationAccess().getNameAssignment_1(), "rule__AuthenticationDeclaration__NameAssignment_1");
					put(grammarAccess.getAuthenticationDeclarationAccess().getPrincipalAssignment_4(), "rule__AuthenticationDeclaration__PrincipalAssignment_4");
					put(grammarAccess.getAuthenticationDeclarationAccess().getCredentialAssignment_6(), "rule__AuthenticationDeclaration__CredentialAssignment_6");
					put(grammarAccess.getAuthenticationParameterAccess().getNameAssignment_0(), "rule__AuthenticationParameter__NameAssignment_0");
					put(grammarAccess.getAuthenticationParameterAccess().getTypeAssignment_2(), "rule__AuthenticationParameter__TypeAssignment_2");
					put(grammarAccess.getInterfaceAccess().getNameAssignment_1(), "rule__Interface__NameAssignment_1");
					put(grammarAccess.getInterfaceAccess().getMethodAssignment_2(), "rule__Interface__MethodAssignment_2");
					put(grammarAccess.getInterfaceAccess().getInputTypeAssignment_3(), "rule__Interface__InputTypeAssignment_3");
					put(grammarAccess.getInterfaceAccess().getOutputTypeAssignment_4_1(), "rule__Interface__OutputTypeAssignment_4_1");
					put(grammarAccess.getInterfaceAccess().getNotAuthenticatedAssignment_5(), "rule__Interface__NotAuthenticatedAssignment_5");
					put(grammarAccess.getInterfaceAccess().getLegacyServletAssignment_6_1(), "rule__Interface__LegacyServletAssignment_6_1");
					put(grammarAccess.getInterfaceAccess().getDocumentationAssignment_7(), "rule__Interface__DocumentationAssignment_7");
					put(grammarAccess.getLegacyServletAccess().getNameAssignment_1(), "rule__LegacyServlet__NameAssignment_1");
					put(grammarAccess.getLegacyServletAccess().getUrlPatternAssignment_3(), "rule__LegacyServlet__UrlPatternAssignment_3");
					put(grammarAccess.getLegacyServletAccess().getFqClassNameAssignment_5(), "rule__LegacyServlet__FqClassNameAssignment_5");
					put(grammarAccess.getCrudServiceAccess().getStructureAssignment_1(), "rule__CrudService__StructureAssignment_1");
					put(grammarAccess.getCrudServiceAccess().getServicesAssignment_3(), "rule__CrudService__ServicesAssignment_3");
					put(grammarAccess.getStructureModelAccess().getTypeDefinitionsAssignment(), "rule__StructureModel__TypeDefinitionsAssignment");
					put(grammarAccess.getStructureDefinitionAccess().getNameAssignment_1(), "rule__StructureDefinition__NameAssignment_1");
					put(grammarAccess.getStructureDefinitionAccess().getPersistentAssignment_2(), "rule__StructureDefinition__PersistentAssignment_2");
					put(grammarAccess.getStructureDefinitionAccess().getFeaturesAssignment_4(), "rule__StructureDefinition__FeaturesAssignment_4");
					put(grammarAccess.getFeatureAccess().getNameAssignment_0(), "rule__Feature__NameAssignment_0");
					put(grammarAccess.getFeatureAccess().getOptionalAssignment_1(), "rule__Feature__OptionalAssignment_1");
					put(grammarAccess.getFeatureAccess().getTypeAssignment_3(), "rule__Feature__TypeAssignment_3");
					put(grammarAccess.getEnumerationDefinitionAccess().getNameAssignment_1(), "rule__EnumerationDefinition__NameAssignment_1");
					put(grammarAccess.getEnumerationDefinitionAccess().getLiteralsAssignment_3(), "rule__EnumerationDefinition__LiteralsAssignment_3");
					put(grammarAccess.getEnumerationLiteralAccess().getNameAssignment_0(), "rule__EnumerationLiteral__NameAssignment_0");
					put(grammarAccess.getEnumerationLiteralAccess().getDisplayNameAssignment_2(), "rule__EnumerationLiteral__DisplayNameAssignment_2");
					put(grammarAccess.getBuiltinTypeLiteralAccess().getBuiltinAssignment(), "rule__BuiltinTypeLiteral__BuiltinAssignment");
					put(grammarAccess.getDefinedTypeLiteralAccess().getTypeAssignment(), "rule__DefinedTypeLiteral__TypeAssignment");
					put(grammarAccess.getListTypeLiteralAccess().getItemTypeAssignment_1(), "rule__ListTypeLiteral__ItemTypeAssignment_1");
					put(grammarAccess.getBackendModelAccess().getUnorderedGroup_1(), "rule__BackendModel__UnorderedGroup_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			nl.dslmeinte.simscript.backend.ui.contentassist.antlr.internal.InternalSimBackendDslParser typedParser = (nl.dslmeinte.simscript.backend.ui.contentassist.antlr.internal.InternalSimBackendDslParser) parser;
			typedParser.entryRuleBackendModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public SimBackendDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SimBackendDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
