/*
 * generated by Xtext
 */
package nl.dslmeinte.simscript.ui.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SimUiDslUiModule extends nl.dslmeinte.simscript.ui.ui.AbstractSimUiDslUiModule {
	public SimUiDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
