/*
 * generated by Xtext
 */
package nl.dslmeinte.simscript.application;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SimApplicationDslRuntimeModule extends nl.dslmeinte.simscript.application.AbstractSimApplicationDslRuntimeModule {

}
