/*
 * generated by Xtext
 */
package com.simlike.simscript.application.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SimApplicationDslUiModule extends com.simlike.simscript.application.ui.AbstractSimApplicationDslUiModule {
	public SimApplicationDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
