/*
* generated by Xtext
*/
package nl.dslmeinte.simscript.application.validation;
 
import java.util.ArrayList;
import java.util.List;

import org.eclipse.emf.ecore.EPackage;

public class AbstractSimApplicationDslJavaValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(nl.dslmeinte.simscript.application.simApplicationDsl.SimApplicationDslPackage.eINSTANCE);
		return result;
	}

}
