/*
 * generated by Xtext
 */
package nl.dslmeinte.simscript.application.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SimApplicationDslUiModule extends nl.dslmeinte.simscript.application.ui.AbstractSimApplicationDslUiModule {
	public SimApplicationDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
